#!/usr/bin/env python3

import sys
import math

# Usage
# ---------------------------------------------------------------------- #

def help():
    print("USAGE")
    print("\t./205IQ u s [IQ1] [IQ2]\n")
    print("DESCRIPTION")
    print("\tu\tmean\n\ts\tstandard deviation")
    print("\tIQ1\tminimum IQ\n\tIQ2\tmaximum IQ")

# Calculation
# ---------------------------------------------------------------------- #

class IQ():
    def __init__(self, avg, std_deviation, min = 0, max = 201):
        if avg < 0 or std_deviation < 0 or min < 0 or max < 0 or max > 201 or avg > 200:
            exit(84)
        self.std_deviation = std_deviation
        self.avg = avg
        self.min = min
        self.max = max
        self.tab = []
        for i in range(self.min, self.max):
            self.tab.append(result(self.avg, self.std_deviation, i))

def result(avg, std_deviation, x):
    return (math.exp(-pow(x - avg, 2) / (2 * pow(std_deviation, 2))) / (std_deviation * math.sqrt(2 * math.pi)))

def basicIQ(iq):
    for i in range(len(iq.tab)):
        print(i, "%.5f" % iq.tab[i])

def minIQ(iq):
    i = 0
    res = 0
    while i < iq.min:
        res += result(iq.avg, iq.std_deviation, i)
        i += 0.01
    print("%.1f%% of people have an IQ inferior to %d" % (res, iq.min))

def intervalIQ(iq):
    i = iq.min
    res = 0
    while i < iq.max:
        res += result(iq.avg, iq.std_deviation, i)
        i += 0.01
    print("%.1f%% of people have an IQ between %d and %d" % (res, iq.min, iq.max))

# Error handling and parsing
# ---------------------------------------------------------------------- #

if len(sys.argv) == 2:
    if sys.argv[1] == "-h":
        help()
    else:
        exit(84)
elif len(sys.argv) == 3:
    iq = IQ(int(sys.argv[1]), int(sys.argv[2]))
    basicIQ(iq)
elif len(sys.argv) == 4:
    iq = IQ(int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3]))
    minIQ(iq)
elif len(sys.argv) == 5:
    iq = IQ(int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4]))
    intervalIQ(iq)
else:
    exit(84)